python3 parse_results_generic_optimized.py pyjelly_235 only_mock_part
python3 parse_results_generic_optimized.py ert_11206 only_mock_part
python3 parse_results_generic_optimized.py vulnerablecode_490  only_mock_part
python3 parse_results_generic_optimized.py autosubmit_2367  only_mock_part
python3 parse_results_generic_optimized.py blueprints_691  only_mock_part
python3 parse_results_generic_optimized.py ophyd-async_316  only_mock_part
python3 parse_results_generic_optimized.py quant-mind_58 only_mock_part
python3 parse_results_generic_optimized.py nipoppy_697 only_mock_part
